pipelines:
  faas-test:
    materials:
      faas-test-git:  # this is the name of material
        # says about type of material and url at once
        git: http://github.com/dantame/faas-test.git
    stages:
      - build: # name of stage
          jobs:
            get-faas-cli: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: curl -sSL https://cli.openfaas.com | sudo sh
            build-image:
              tasks:
              - exec:
                   command: faas-cli build --shrinkwrap
            push-image:
              tasks:
              - exec:
                   command: faas-cli push
            deploy-image:
              tasks:
              - exec:
                   command: faas-cli deploy
