---
resource_types:
- name: concourse-pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource

resources:
  - name: faas-test-pipeline
    type: concourse-pipeline
    source:
      teams:
      - name: main
  - name: faas-test
    type: git
    icon: github-circle
    source:
      uri: https://github.com/dantame/faas-test

jobs:
- name: update-faas-test-pipeline
  plan:
  - get: faas-test
  - put: faas-test-pipeline
    params:
      pipelines:
      - name: faas-test
        team: main
        config_file: ./pipeline.yml
